namespace SwfLib.Avm2 {
    public enum AsType : byte {

        Void = 0x00,  
        Undefined = Void,
        Utf8 = 0x01,
        Decimal = 0x02,
        Integer = 0x03,
        UInteger = 0x04,
        PrivateNamespace = 0x05,
        Double = 0x06,
        QName = 0x07, 
        Namespace = 0x08,
        Multiname = 0x09,
        False = 0x0A,
        True = 0x0B,
        Null = 0x0C,
        QNameA = 0x0D,   
        MultinameA = 0x0E,
        RTQName = 0x0F,   
        RTQNameA = 0x10,  
        RTQNameL = 0x11,  
        RTQNameLA = 0x12, 
        Namespace_Set = 0x15, 
        PackageNamespace = 0x16, 
        PackageInternalNs = 0x17,
        ProtectedNamespace = 0x18,
        ExplicitNamespace = 0x19,
        StaticProtectedNs = 0x1A,
        MultinameL = 0x1B,
        MultinameLA = 0x1C,
        TypeName = 0x1D,
        Max
    }
}
